Feature presidecms 576 asset manager issue
pixl8/Preside-CMS pull request #197
Opened 2016-10-13 02:50 UTC by tommyw1314

fix error on duplicated file exist in target folder

2016-10-13 12:49 UTC, DominicWatson requested changes
_Deleting this review to try again properly_ (nothing to see here)

2016-10-13 12:51 UTC, DominicWatson approved these changes

2016-10-13 12:54 UTC, DominicWatson requested changes
I believe there are some issues around the logic used to check uniqueness of assets within a folder. Please see review comments.

2016-10-13 12:54 UTC, DominicWatson commented on system/services/assetManager/AssetManagerService.cfc
> +		,          string  assetId
This argument should either be required or have a default value (""). I think it should probably be required.

2016-10-13 12:54 UTC, DominicWatson commented on system/services/assetManager/AssetManagerService.cfc
> +		var fileExist      = _getAssetDao().dataExists( filter = { id = arguments.assetId } );
What we should be checking for here is that _another_ asset does not already exist in the new folder that has the same _name_ as the current asset.

If we just check for the existance of the asset, then we will never be able to move assets between folders.

2016-10-24 07:14 UTC, tommyw1314 commented
i have removed the assetId and do checking based on the asset_folder & title.

2017-01-30 12:51 UTC, DominicWatson commented
Great, thanks @tommyw1314. Merging into the upcoming release.

2017-04-26 21:38 UTC, merged