PRESIDECMS-345 : Make user group as required for admin users.
pixl8/Preside-CMS pull request #203
Opened 2016-10-24 13:55 UTC by cfmitrah

2016-12-16 10:49 UTC, DominicWatson requested changes
Looking good, but please see review comment.

2016-12-16 10:49 UTC, DominicWatson commented on system/forms/preside-objects/security_user/admin.edit.self.xml
> +			<field binding="security_user.groups" required="false"/>
A user should not be able to edit their own groups :) Please remove this line.

2016-12-16 11:16 UTC, cfmitrah commented on system/forms/preside-objects/security_user/admin.edit.self.xml
> +			<field binding="security_user.groups" required="false"/>
Removed edit functionality for user group

2017-01-27 15:21 UTC, DominicWatson commented
Nice one, thanks for this. Merged into the upcoming 10.8.0 release.

2017-04-26 21:38 UTC, merged