PRESIDECMS-626 : Added the message column on error log listing page.
pixl8/Preside-CMS pull request #209
Opened 2016-11-16 10:53 UTC by cfmitrah

2016-12-16 10:45 UTC, DominicWatson requested changes
Looking good Selva, thank you. Please see the review comments - a couple of minor points.

2016-12-16 10:45 UTC, DominicWatson commented on system/services/errors/ErrorLogService.cfc
> +			var messageContent = ReplaceList( errorMessage[1] , "<title>,</title>", "#chr(10)# ,#chr(10)#" );
We ought to be a little careful here. What if, for whatever reason, `REMatchNoCase()` returns an empty array here? 

Perhaps: 
```
var messageContent = errorMessage.len() ? ReplaceList( errorMessage[1] , "<title>,</title>", "#chr(10)# ,#chr(10)#" ) : "";
```

2016-12-16 10:45 UTC, DominicWatson commented on system/views/admin/errorLogs/index.cfm
> +							#left( log.message, "30" )#...<span class="fa fa-caret-down" data-rel="popover" data-trigger="hover" data-placement="left" data-content="<pre>#log.message#</pre>" data-html="true"></span>
We need to make sure that we escape the log message when inserting as an attribute in HTML:

```
... data-content="#HtmlEditFormat( '<pre>#log.message#</pre>' )#" ...
```
```

2016-12-16 13:42 UTC, cfmitrah commented on system/services/errors/ErrorLogService.cfc
> +			var messageContent = ReplaceList( errorMessage[1] , "<title>,</title>", "#chr(10)# ,#chr(10)#" );
Updated messageContent for avoid empty array.

2016-12-16 13:43 UTC, cfmitrah commented on system/views/admin/errorLogs/index.cfm
> +							#left( log.message, "30" )#...<span class="fa fa-caret-down" data-rel="popover" data-trigger="hover" data-placement="left" data-content="<pre>#log.message#</pre>" data-html="true"></span>
Used HTML attribute for log message.

2017-01-27 16:38 UTC, DominicWatson commented
Nice one, thanks @cfmitrah. Merging into upcoming release (10.8.0)

2017-01-27 16:38 UTC, DominicWatson approved these changes

2017-04-26 21:38 UTC, merged