PRESIDECMS-651: Implemented clone form functionalities.
pixl8/Preside-CMS pull request #211
Opened 2016-11-25 07:46 UTC by cfmitrah

2016-11-25 08:59 UTC, DominicWatson commented on system/services/formbuilder/FormBuilderService.cfc
> +					cloneFormData[ "#column#" ] = arguments[ "#column#" ];
`cloneFormData[ "#column#" ]` should just be `cloneFormData[ column ]` (same for `arguments[ column ]). See also lines below.

2016-11-25 09:02 UTC, DominicWatson requested changes
Hey Mani, this is looking really great, thank you. Please see the review comments - a couple of minor tweaks, mostly just tidying.

Thanks!

2016-11-25 09:02 UTC, DominicWatson commented on system/views/admin/formbuilder/cloneForm.cfm
> +	var formId = createUUID();
This has the potential to create invalid HTML element IDs (they must not start with a number). I think ok to use "formbuilder-clone-form" or somesuch here.

2016-11-25 09:02 UTC, DominicWatson commented on system/services/formbuilder/FormBuilderService.cfc
> +		var cloneFormData = structNew();
Here, I think this is more accurate:

```
var cloneFormData = { name=arguments.name, description=arguments.description };
```

Then further down, when you loop over the `originalFormData.columnList`, you can ignore these fields and remove the logic on line 972-3.

2016-11-25 09:02 UTC, DominicWatson commented on system/services/formbuilder/FormBuilderService.cfc
> +				if( listFindNoCase( "name,description", column ) ) {
See comment above

2016-11-25 14:51 UTC, cfmitrah commented
@DominicWatson  
	* Created valid HTML element IDs, using "formbuilder-clone-form".
	* Simplified the code while looping 'originalFormData.columnList'

2016-11-26 05:21 UTC, cfmitrah commented on system/views/admin/formbuilder/cloneForm.cfm
> +	var formId = createUUID();
Created valid HTML element IDs, using "formbuilder-clone-form".

2016-11-26 05:24 UTC, cfmitrah commented on system/services/formbuilder/FormBuilderService.cfc
> +		var cloneFormData = structNew();
Simplified the code while looping 'originalFormData.columnList' by 
<code>var cloneFormData = { name=arguments.name, description=arguments.description };</code>

2017-01-30 12:08 UTC, DominicWatson commented
Super, thanks @cfmitrah. Merged into upcoming release.

2017-04-26 21:38 UTC, merged