PRESIDECMS-656
pixl8/Preside-CMS pull request #212
Opened 2016-11-29 06:59 UTC by john5onCheng

Ensures object picker is able to filter from related simple value field.

2016-12-01 04:23 UTC, john5onCheng commented
Hi Dom, I've revert previous changes and apply the recommended approach.

2016-12-05 17:39 UTC, DominicWatson commented
This looks about right - I tried it out locally though and couldn't get it to work. There are a few things here that I'd refactor too. Let's take a look together as soon as reasonable.

2016-12-21 06:22 UTC, john5onCheng commented
Hi Dom, I've found the error that you mentioned and have get it fixed. Please let me know which line you would like to refactor.

2016-12-21 09:23 UTC, DominicWatson requested changes
Looking good, please see review comments re points that need refactoring.

2016-12-21 09:23 UTC, DominicWatson commented on system/handlers/admin/DataManager.cfc
> +			loop list=filterByField index="indexField"{
`indexField` is not `var'd` here and I would avoid looping a list - especially using cfloop syntax. Prefer this:

```
var filterByFields = ListToArray( rc.filterByField ?: "" );
for( var filterByField in filterByFields ) {
    // ...
}
```

2016-12-21 09:23 UTC, DominicWatson commented on system/assets/js/admin/presidecore/preside.uber.select.js
> +			var remote_url   = this.form_field.getAttribute( "data-remote-url" );
in our *js*, we'd like `var` definitions at the _top_ of functions and using the style:

```
var variable1 = true
  , variable2 = false
  , variable3, variable 4; // not yet set vars
```

These vars should be moved up aroud line 355 (and declared in the list style).

2016-12-21 09:23 UTC, DominicWatson commented on system/assets/js/admin/presidecore/preside.uber.select.js
> +			var filterBy        = this.form_field.getAttribute( "data-filter-by" );
All the `var` definitions should be moved to the top of the function here:

```
var filterBy        = this.form_field.getAttribute( "data-filter-by" )
  , filterByField   = this.form_field.getAttribute( "data-filter-by-field" )
  , filterByValue;

this.filter       = "";
this.filter_field = $( "input[name='" + filterBy + "']" );

filterByValue = this.filter_field.val();
if ( typeof filterByValue !== "undefined" ) {
// ...
}
```

2016-12-21 10:40 UTC, john5onCheng commented
hi Dom, requested changes has been made

2016-12-21 10:50 UTC, DominicWatson approved these changes

2016-12-21 10:50 UTC, DominicWatson commented
Perfect, testing now.

2016-12-21 11:28 UTC, merged