PRESIDECMS-608 One-to-many configurator form control
pixl8/Preside-CMS pull request #262
Opened 2017-02-22 14:28 UTC by sebduggan

2017-02-22 14:46 UTC, DominicWatson commented on system/handlers/formcontrols/OneToManyConfigurator.cfc
> +				, selectFields     = [ "id", "label" ]
what happens here when the target object uses a label field other than "label", or doesn't have a label field at all? We _can_ use:

```
[ "id", "${labelfield} as label" ]
```

But perhaps it makes sense just to select all fields by not supplying a select fields array at all?

2017-02-28 09:11 UTC, DominicWatson requested changes
Looks great but for the forms service injection which we can discuss later if needed (though I think is safe to remove).

Also a bit of debugging left over in the js :)

2017-02-28 09:11 UTC, DominicWatson commented on system/assets/js/admin/specific/datamanager/configuratorForm/configuratorFormHandler.js
> +			console.log(formData);
Some debugging left over ;)

2017-02-28 09:11 UTC, DominicWatson commented on system/services/presideObjects/PresideObjectService.cfc
> +			var formName = record.configurator__formname ?: "";
I'd like to remove this logic if possible. Is the purpose to ensure that checkbox boolean fields have a present variable? I think this logic is the responsibility of the code that prepares the json (i.e. all the required fields should be present and its not the responsibility of the preside object service to start validating the input).

I think this should be safe to remove altogether (along with the line that gets the forms service). Or is this logic absolutely required?

2017-02-28 09:31 UTC, sebduggan commented on system/assets/js/admin/specific/datamanager/configuratorForm/configuratorFormHandler.js
> +			console.log(formData);
Oops...

2017-02-28 09:32 UTC, sebduggan commented on system/services/presideObjects/PresideObjectService.cfc
> +			var formName = record.configurator__formname ?: "";
You're right, it was just there to ensure unchecked checkboxes were recorded. Now implemented in the Javascript.

2017-02-28 11:48 UTC, DominicWatson commented
Nice one, thanks @sebduggan. Merging into upcoming 10.8 :)

2017-02-28 11:56 UTC, merged