Feature presidecms 1187 datetime picker related to field
pixl8/Preside-CMS pull request #467
Opened 2018-04-24 09:56 UTC by nelsonchuah

Add relatedTo functionality to datetimePicker 

and fix minor issue on datepicker js
- `currentDate.setDate( currentDate - 1 );` should be `currentDate.setDate( currentDate.getDate() - 1 );`

2018-04-24 16:01 UTC, DominicWatson requested changes
This looks brilliant, thanks Nelson. Could you just fix up the indentation and we can get this merged?

2018-04-24 16:01 UTC, DominicWatson commented on system/assets/js/admin/presidecore/preside.datetimepicker.js
> +                  time:     'fa fa-clock-o'
Could you fix the indentation / whitespace here? Seems to go awry in the icons section.

2018-04-25 01:44 UTC, nelsonchuah commented
Hi Dom,

Have fixed the indentation 

Thank you
Nelson

2018-04-25 09:34 UTC, merged

2018-04-25 09:34 UTC, sebduggan commented
Thanks @nelsonchuah  - good work!