Feature presidecms 884 resend token
pixl8/Preside-CMS pull request #487
Opened 2018-05-07 06:47 UTC by annbelievable

2018-05-08 08:05 UTC, DominicWatson requested changes
Hey @annbelievable, thanks for this, looking good :)

A functional change I'd like to make, however, is that I don't think should be a scheduled task. Instead, it should trigger when a user attempts to reset password with an expired token.

The message would then say something like: "Your token has expired, we've sent you another one..." (you wouldn't need to change anything here, this would be editorial, of course).

2018-05-08 08:05 UTC, DominicWatson commented on system/handlers/Tasks.cfc
> +
I'm not sure that we should send this out on a schedule. I think more preferable would be to resend only when they attempt to reset their password with an expired token.

2018-05-09 07:16 UTC, annbelievable commented
Removed the scheduled task, send out the email once an expired token is detected (when validating the reset password token).

2018-05-09 13:14 UTC, DominicWatson commented
Nice one, thanks @annbelievable. I've created a new feature branch in Preside (`feature-PRESIDECMS-884_resend_token`) and made a few changes (renamed some things, fixed some tests, etc.).

It would be great to start a new Pull request from and to that new branch with following ammendments:

* Add the same functionality to the admin
* Allow turning the feature on/off using a feature flag. Default should be "off". This is because any existing messaging around token expiry will be aligned with not using this feature so those upgrading will have a "broken" user experience

2018-05-09 13:14 UTC, closed without merging