feature_PRESIDECMS-915 ::
pixl8/Preside-CMS pull request #509
Opened 2018-05-28 15:05 UTC by cfmitrah

- Remove unwanted \n \t from json ajaxproxy results.

2018-06-07 13:13 UTC, DominicWatson requested changes
Hi guys, thanks for this - could you take a look at the review feedback?

2018-06-07 13:13 UTC, DominicWatson commented on system/services/helpers/JQueryDatatablesHelpers.cfc
> +		if( isStruct( result.aaData[1] ) AND result.aaData[1]._options NEQ '' )
I'm not sure about this. Firstly:

* This presumably should be run against each row
* The cleanup needs to be a little smarter than just removing all whitespace?

I imagine the whitespace cleanup would be something like:

```reReplace( result.aaData[ i ]._options, "\s+", " ", "all" )

(i.e. tidyup double spaces, not get rid of all).

Would be good to see some before and after output after making this fix.

2018-06-11 07:32 UTC, cfmitrah commented
- Functionality optimized. ( now it's  run against each row )
- yes that functionality removing all white space.
- I've attached screen samples for before and after changes.
**Before change :** 
![before](https://user-images.githubusercontent.com/532401/41218028-5fe2745c-6d77-11e8-9b6b-9a8be0b8602e.JPG)

**After change :**

![after](https://user-images.githubusercontent.com/532401/41218055-7578b772-6d77-11e8-9c8c-14971d5bd510.JPG)

Please check that and let me know if any update needed ?

2018-06-11 08:01 UTC, DominicWatson commented
The issue with removing _all_ whitespace is that text gets broken. There can be editorial text in the return (as in your example) and all the spaces are removed from that.

So, yes - needs to not remove _all_ whitespace, but rather convert 1 or more consecutive whitespace characters into a single whitespace character.

2018-06-15 11:23 UTC, closed without merging

2018-06-15 11:42 UTC, DominicWatson commented
Garrrr, this got auto closed because the target branch has disappeared. Really sorry for this. You should be able to re-open from your branch though by targeting the `stable` branch.