feature_PRESIDECMS-1252 ::
pixl8/Preside-CMS pull request #513
Opened 2018-05-30 16:14 UTC by cfmitrah

- Fixed UI overlaps issue.

2018-06-07 13:29 UTC, DominicWatson requested changes
Thanks @cfmitrah - please see review comments.

2018-06-07 13:29 UTC, DominicWatson commented on system/views/admin/rulesEngine/index.cfm
> +	<div class="top-right-button-group" style="margin: -8px 4px 0px 0px;">
Not sure on this one. I think we need a global fix for this issue with the 'top-right-button-group'. i.e. some kind of `event.addAdminTopRightButton()`, `event.getAdminTopRightButtons()` set of methods. These could then be output at the very end of the request in a CSS layout that doesn't require absolute positioning.

Can you remove this bit from the PR and we can then merge the other change?

2018-06-11 07:49 UTC, cfmitrah commented
> Can you remove this bit from the PR and we can then merge the other change?

Yes We removed that inline style, You can merge other change.

2018-06-15 11:23 UTC, closed without merging

2018-06-15 11:42 UTC, DominicWatson commented
Garrrr, this got auto closed because the target branch has disappeared. Really sorry for this. You should be able to re-open from your branch though by targeting the `stable` branch.